# Generated by Django 6.0.2 on 2026-04-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0003_servicio_alter_renglon_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('tercer_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('apellido_casada', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('dpi', models.CharField(max_length=13, unique=True)),
                ('correo', models.EmailField(max_length=120, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='personas/')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('departamento', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
