# Generated by Django 6.0.2 on 2026-04-01 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0004_persona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('numero_empleado', models.CharField(max_length=20, unique=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('puesto_oficial', models.CharField(blank=True, max_length=100, null=True)),
                ('especializacion', models.CharField(blank=True, max_length=100, null=True)),
                ('colegiado_activo', models.CharField(blank=True, max_length=30, null=True)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=150, null=True)),
                ('comisionado_seccion_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('comisionado_seccion_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_creados', to=settings.AUTH_USER_MODEL)),
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.RESTRICT, to='organizacion.persona')),
                ('id_renglon', models.ForeignKey(blank=True, db_column='id_renglon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.renglon')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.servicio')),
                ('id_usuario', models.OneToOneField(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
