# Generated by Django 6.0.2 on 2026-04-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0005_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='organizacion.empleado')),
                ('id_renglon', models.ForeignKey(blank=True, db_column='id_renglon', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.renglon')),
                ('id_servicio', models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.servicio')),
            ],
        ),
    ]
