# Generated by Django 6.0.2 on 2026-04-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0006_contrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id_permiso', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_requerida', models.DateField()),
                ('dias_solicitados', models.PositiveIntegerField(default=1)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('documento', models.FileField(blank=True, null=True, upload_to='permisos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='organizacion.empleado')),
            ],
            options={
                'db_table': 'permisos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
