# Generated by Django 6.0.2 on 2026-04-21 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0008_vacacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_sancion', models.DateField()),
                ('detalle', models.TextField(max_length=500)),
                ('documento', models.FileField(blank=True, null=True, upload_to='sanciones/')),
                ('activo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='organizacion.empleado')),
            ],
            options={
                'db_table': 'sanciones',
                'ordering': ['-fecha_sancion'],
            },
        ),
    ]
