# Generated by Django 6.0.2 on 2026-04-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0010_empleado_salario_permiso_autorizado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoPersonal',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ENTREGA_PUESTO', 'Entrega de Puesto'), ('TOMA_PUESTO', 'Toma de Puesto')], max_length=20)),
                ('fecha_efectiva', models.DateField()),
                ('descripcion', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='organizacion.empleado')),
            ],
            options={
                'db_table': 'movimientos_personal',
                'ordering': ['-fecha_efectiva'],
            },
        ),
    ]
