# Generated by Django 6.0.2 on 2026-05-03 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0011_movimientopersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientopersonal',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
